### ISSUE TITLE
PnPQ API refactoring

### ISSUE THREAD

**Issue by auspicacious** [moonshot-nagayama-pj/PnPQ#27]
- [x] https://github.com/moonshot-nagayama-pj/PnPQ/issues/29
- [x] https://github.com/moonshot-nagayama-pj/PnPQ/issues/28
- [x] https://github.com/moonshot-nagayama-pj/PnPQ/issues/86
- [x] https://github.com/moonshot-nagayama-pj/PnPQ/issues/92

**Comment by master-of-ppap** [comment]
@auspicacious would it be possible to close this issue now? I think we’ve done everything.

**Comment by auspicacious** [comment]
Closing in favor of continuation in https://github.com/moonshot-nagayama-pj/PnPQ/issues/118
